### ISSUE TITLE
correction

### ISSUE THREAD

**Issue by aswinpradeep** [sanket9918/Lenovo-ideapad-330-ARR-issues#1]
After almost 1 months of hardwork!!I literally made a nearly stable dual boot setup.Try my methods,worked fine with moth Linux mint 19 and Ubuntu 18.04(present setup)

 

1.Go to bios and disable each and everything related to legacy boot.Resetting bios settings won't disable everything necessary.Whatever you do other than this method you won't be able to install Ubuntu in uefi mode.in legacy mode proper working not possible to do without nomodeset parameter..So better do this.

 

2.Live boot to Ubuntu.Make sure you are in uefi mode(google).Install it .Take care to create a seperate partition for boot field.

 

3.Reboot and install windows 10 in Uefi mode.use f12 ro change boot options.

 

4.Now pressing f12 at reboot time will show up both Linux and windows partitions.boot to Linux.Download and compile 4.17.x kernel  after making changes as I have instructed in above comment^^

 

5.Boot to the new kernel and you can see touchpad working(verified in Linux mint 19) .now install appropriate wifi driver(name in above comment^ ending with CE).After a reboot if things are fine,brightness,wifi and touchpad will be working fine

 

6.Grub might have been fixed automatically by now on trying to update kernel.If not,try installing Anbox emulator grub will be installed on updating some headers

 

 

😊 GOOD LUCK.Do share with me if the steps worked for you

**Comment by sanket9918** [comment]
The main problems were encountered during the installation was the problem regarding the partial support in the Linux kernel.

The latest Linux kernel version 5 which comes with the Ubuntu 19.04 , has this driver pre loaded and this will resolve the issues that you were currently encountering (atleast the mouse is working fine without any kind of fix)

I successfully setup my computer with the dual boot option on the Windows 10 and Ubuntu in the uefi mode as it is completely safe now and this much better than the legacy mode because the full capability of your laptop unleashes in this mode. the booting time of the operating systems is much better.

If you have any other query regarding this please let me know.
